# Generated by Django 3.2.7 on 2021-11-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JupiterLibrary', '0004_auto_20211110_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publicationDate',
            new_name='date',
        ),
    ]
