# Generated by Django 3.2.7 on 2021-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JupiterLibrary', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numberAvailable',
            field=models.PositiveBigIntegerField(verbose_name='Number Available'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numberBorrowed',
            field=models.PositiveBigIntegerField(verbose_name='Number Borrowed'),
        ),
    ]
