# Generated by Django 3.2.7 on 2021-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JupiterLibrary', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
