# Generated by Django 3.2.7 on 2021-11-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JupiterLibrary', '0008_auto_20211113_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bid',
        ),
    ]
