# Generated by Django 3.2.7 on 2021-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JupiterLibrary', '0008_auto_20211121_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
            ],
        ),
    ]
