# Generated by Django 3.2.7 on 2021-11-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JupiterLibrary', '0010_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
    ]
